# Generated by Django 2.2.4 on 2019-08-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acelerometro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('eixoX', models.BooleanField()),
                ('eixoY', models.BooleanField()),
                ('eixoZ', models.BooleanField()),
            ],
        ),
    ]
