# Generated by Django 2.2.4 on 2019-08-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('documento', models.FileField(upload_to='', verbose_name='Arquivo')),
                ('canais', models.IntegerField(verbose_name='Canais')),
                ('dataLeitura', models.DateField(verbose_name='Data de Leituras')),
                ('dataUpload', models.DateField(auto_now=True, verbose_name='Data de Upload')),
            ],
            options={
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.AlterModelOptions(
            name='acelerometro',
            options={'verbose_name': 'Acelerômetro', 'verbose_name_plural': 'Acelerômetros'},
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='eixoX',
            field=models.BooleanField(verbose_name='Eixo X'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='eixoY',
            field=models.BooleanField(verbose_name='Eixo Y'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='eixoZ',
            field=models.BooleanField(verbose_name='Eixo Z'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='localizacao',
            field=models.CharField(max_length=100, verbose_name='Localização'),
        ),
    ]
