# Generated by Django 2.2.4 on 2019-08-29 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190828_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivo',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AddField(
            model_name='arquivo',
            name='acelerometro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='acelerometro_arquivo', to='core.Acelerometro', verbose_name='Acelerômetro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivo',
            name='frequencia',
            field=models.IntegerField(default=0, verbose_name='Frequência em Hz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataLeitura',
            field=models.DateField(verbose_name='Data/hora da leitura inicial'),
        ),
    ]
