# Generated by Django 2.2.4 on 2019-09-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190831_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='estatistica_curtoses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='estatistica_desvio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='estatistica_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='estatistica_variancia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='estatisticas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(choices=[('UEME', 'UEME'), ('OUTRO', 'OUTRO')], default='OUTRO', max_length=10),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
