# Generated by Django 2.2.5 on 2019-09-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190923_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourier_size', models.IntegerField()),
                ('channels', models.IntegerField()),
                ('channels_analysis', models.IntegerField()),
                ('graph', models.ImageField(upload_to='graph_images')),
                ('accelerometer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Acelerometro')),
            ],
        ),
    ]
