# Generated by Django 2.2.4 on 2019-08-29 16:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190829_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='dataLeitura',
            field=models.DateTimeField(verbose_name='Data/hora da leitura inicial'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataUpload',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Upload'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='documento',
            field=models.FileField(upload_to=core.models.Arquivo.file_directory_path, verbose_name='Arquivo'),
        ),
    ]
