# Generated by Django 2.2.4 on 2019-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190907_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='estatistica_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
