# Generated by Django 2.2.5 on 2019-09-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_graphresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphresults',
            name='accelerometer',
        ),
        migrations.AddField(
            model_name='graphresults',
            name='archiev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Arquivo'),
            preserve_default=False,
        ),
    ]
