# Generated by Django 2.2.5 on 2019-10-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190930_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphresults',
            name='graph',
            field=models.ImageField(upload_to='graph_images/'),
        ),
    ]
