# Generated by Django 2.2.4 on 2019-09-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_leituraueme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeituraUEME',
        ),
    ]
