# Generated by Django 2.2.1 on 2019-11-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191101_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphresults',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='graphresults',
            name='graph',
            field=models.ImageField(upload_to='graph_images'),
        ),
    ]
