# Generated by Django 2.2.4 on 2019-09-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_leituraueme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='estatistica_curtoses',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='estatistica_desvio',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='estatistica_media',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='estatistica_variancia',
        ),
        migrations.CreateModel(
            name='ArquivoEstatisticas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('canal', models.SmallIntegerField(default=1)),
                ('media', models.FloatField(blank=True, null=True)),
                ('desvio', models.FloatField(blank=True, null=True)),
                ('variancia', models.FloatField(blank=True, null=True)),
                ('curtoses', models.FloatField(blank=True, null=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo_estatistica', to='core.Arquivo')),
            ],
        ),
    ]
