# Generated by Django 2.2.1 on 2019-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191111_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphresults',
            name='time',
            field=models.IntegerField(null=True, verbose_name='ToTAL PROCESS TIME'),
        ),
    ]
