# Generated by Django 2.2.4 on 2019-09-15 18:49

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190908_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acelerometro',
            options={'verbose_name': 'Accelerometer', 'verbose_name_plural': 'Accelerometers'},
        ),
        migrations.AlterModelOptions(
            name='arquivo',
            options={'verbose_name': 'Archive', 'verbose_name_plural': 'Archives'},
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='eixoX',
            field=models.BooleanField(verbose_name='Axis X'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='eixoY',
            field=models.BooleanField(verbose_name='Axis Y'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='eixoZ',
            field=models.BooleanField(verbose_name='Axis Z'),
        ),
        migrations.AlterField(
            model_name='acelerometro',
            name='localizacao',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='acelerometro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acelerometro_arquivo', to='core.Acelerometro', verbose_name='Accelerometer'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='canais',
            field=models.IntegerField(verbose_name='Channels'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataLeitura',
            field=models.DateTimeField(verbose_name='Date / time of initial reading'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='dataUpload',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='documento',
            field=models.FileField(upload_to=core.models.Arquivo.file_directory_path, verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='estatistica_observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='estatisticas',
            field=models.BooleanField(default=False, verbose_name='Kurtosis'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='frequencia',
            field=models.IntegerField(verbose_name='Frequency in Hz'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(choices=[('UEME', 'UEME'), ('OTHER', 'OTHER')], default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='arquivoestatisticas',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo_estatistica', to='core.Arquivo', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='arquivoestatisticas',
            name='canal',
            field=models.SmallIntegerField(default=1, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='arquivoestatisticas',
            name='curtoses',
            field=models.FloatField(blank=True, null=True, verbose_name='Kurtosis'),
        ),
        migrations.AlterField(
            model_name='arquivoestatisticas',
            name='desvio',
            field=models.FloatField(blank=True, null=True, verbose_name='Standard derivation'),
        ),
        migrations.AlterField(
            model_name='arquivoestatisticas',
            name='media',
            field=models.FloatField(blank=True, null=True, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='arquivoestatisticas',
            name='variancia',
            field=models.FloatField(blank=True, null=True, verbose_name='Variance'),
        ),
    ]
