# Generated by Django 2.2.5 on 2019-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190915_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivoestatisticas',
            options={'verbose_name': 'Statistics', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='estatisticas',
            field=models.BooleanField(default=False, verbose_name='Statistics'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(choices=[('UEME', 'UEME'), ('OTHER', 'OTHER')], default='OTHER', max_length=10, verbose_name='Type'),
        ),
    ]
