# Generated by Django 2.2.1 on 2019-11-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191111_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphresults',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
