# Generated by Django 2.2.7 on 2019-11-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191111_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphresults',
            name='callection_date',
            field=models.DateTimeField(null=True),
        ),
    ]
