# Generated by Django 2.2.7 on 2019-11-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_graphresults_callection_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphresults',
            old_name='callection_date',
            new_name='collection_date',
        ),
    ]
